TRANSLATIONS = {
    "az": {
        # General
        "page_title": "Document Navigator",
        "language_select": "Dil seçin",
        
        # Login
        "login_header": "Daxil Olun",
        "login_subheader": "Sistemə daxil olmaq üçün giriş edin",
        "username_label": "İstifadəçi adı",
        "password_label": "Şifrə",
        "login_button": "Daxil ol",
        "invalid_credentials": "İstifadəçi adı və ya şifrə yanlışdır. Yenidən cəhd edin.",
        
        # Main App
        "logout_button": "Çıxış",
        "logged_in_as": "Daxil olub:",
        "nav_header": "Naviqasiya",
        "new_chat_button": "Yeni Söhbət",

        # User Dashboard
        "user_dashboard_title": "İstifadəçi Paneli",
        "user_dashboard_welcome": "Xoş gəlmisiniz! Burada sizin üçün aid olan sənədləri tapa bilərsiniz.",
        "chatbot_welcome_message": "Salam, mən sizin GenAI Document Navigatorunuzam",
        "search_placeholder": "Fayllarınız haqqında bir sual verin...",
        "answer_header": "Cavab",
        "sources_header": "Mənbələr",
        "no_info_found": "Sualınıza uyğun heç bir məlumat tapılmadı.",
        "ask_question_prompt": "Başlamaq üçün bir sual daxil edin.",
        "searching_spinner": "Uyğun məlumat axtarılır...",
        "generating_answer_spinner": "Cavab hazırlanır...",

        "analysis_expander_label": "Müvəqqəti Fayl Analizi (Ümumi Bazaya Əlavə Edilmir)",
        "analysis_info_ready": "analiz üçün hazırdır. Aşağıdakı düymələrdən istifadə edə bilərsiniz.",
        
        # Admin Dashboard
        "admin_dashboard_title": "Admin Panel",
        "admin_dashboard_welcome": "Xoş gəlmisiniz, Admin. Burada bütün faylları yükləyə, baxa və idarə edə bilərsiniz.",
        "upload_tab": "Yüklə",
        "manage_tab": "Bax və İdarə et",
        "bulk_ops_tab": "Toplu Əməliyyatlar",
        "upload_header": "Faylları Yüklə və Teqlə",
        "uploader_label": "Yükləmək üçün faylları seçin",
        "assign_team_label": "Komandaya təyin et:",
        "tags_label": "Teqlər (vergüllə ayırın):",
        "tags_placeholder": "məs., maliyyə, hesabat, r3",
        "selected_files_header": "Seçilmiş Fayllar:",
        "upload_process_button": "Bütün Faylları Yüklə və Emal et",
        "processing_spinner": "Fayllar emal edilir... Bu bir az vaxt apara bilər.",
        "library_header": "Fayl Kitabxanası",
        "filter_type_label": "Növə görə filtr:",
        "search_files_label": "Faylları axtar:",
        "sort_by_label": "Sırala:",
        "found_docs_text": "fayl tapıldı",
        "delete_button_confirm": "⚠️ Əminsiniz? Bu əməliyyat geri qaytarıla bilməz!",
        "delete_all_button": "Bütün Faylları Sil",
        "bulk_ops_header": "Toplu Əməliyyatlar",
        "no_docs_uploaded": "Hələ heç bir fayl yüklənməyib.",
        "no_docs_for_bulk": "Toplu əməliyyatlar üçün heç bir fayl yoxdur.",
        "delete_success": "uğurla silindi!",
        "confirm_delete_all_button": "Bəli, hamısını sil",
        "confirm_delete_single_button": "Bəli, sil",
        "cancel_button": "Ləğv et",
        # "danger_zone": "TƏHLÜKƏLİ ZONA",
        "storage_statistics": "Yaddaş Statistikası",
        "total_documents": "Cəmi Fayl Sayı",
        "total_storage_used": "İstifadə Olunan Həcm",
        "all_files_option": "Hamısı",
        "index_success": "Uğurla indeksləndi",
        "index_fail": "İndeksləmə alınmadı",
    },
    "en": {
        "page_title": "Document Navigator",
        "language_select": "Select Language",
        "login_header": "Login",
        "login_subheader": "Please log in to access the system",
        "username_label": "Username",
        "password_label": "Password",
        "login_button": "Log in",
        "invalid_credentials": "Invalid username or password. Please try again.",
        "logout_button": "Logout",
        "logged_in_as": "Logged in as:",
        "nav_header": "Navigation",
        "new_chat_button": "➕ New Chat",
        "user_dashboard_title": "User Dashboard",
        "user_dashboard_welcome": "Welcome! Here you can find documents relevant to you.",
        "chatbot_welcome_message": "Hello, I am your GenAI Document Navigator",
        "search_placeholder": "Ask a question about your documents...",
        "answer_header": "Answer",
        "sources_header": "Sources",
        "no_info_found": "No relevant information was found for your question.",
        "ask_question_prompt": "Enter a question to get started.",
        "searching_spinner": "Searching for relevant information...",
        "generating_answer_spinner": "Generating answer...",
        "admin_dashboard_title": "Admin Document Management",
        "admin_dashboard_welcome": "Welcome, Admin. Here you can upload, view, and manage all documents.",
        "upload_tab": "Upload",
        "manage_tab": "View & Manage",
        "bulk_ops_tab": "Bulk Operations",
        "upload_header": "Upload, Tag & Process Documents",
        "uploader_label": "Choose files to upload",
        "assign_team_label": "Assign to Team:",
        "tags_label": "Add Tags (comma-separated):",
        "tags_placeholder": "e.g., finance, report, q3",
        "selected_files_header": "Files Selected:",
        "upload_process_button": "Upload & Process All Files",
        "processing_spinner": "Processing files... This may take a moment.",
        "library_header": "Document Library",
        "filter_type_label": "Filter by type:",
        "search_files_label": "Search files:",
        "sort_by_label": "Sort by:",
        "found_docs_text": "document(s) found",
        "delete_button_confirm": "⚠️ Are you sure? This action cannot be undone!",
        "delete_all_button": "Delete All Documents",
        "bulk_ops_header": "Bulk Operations",
        "no_docs_uploaded": "No documents uploaded yet.",
        "no_docs_for_bulk": "No documents available for bulk operations.",
        "delete_success": "deleted successfully!",
        "confirm_delete_all_button": "Yes, Delete All",
        "confirm_delete_single_button": "Yes, delete",
        "cancel_button": "Cancel",
        # "danger_zone": "DANGER ZONE",
        "storage_statistics": "Storage Statistics",
        "total_documents": "Total Documents",
        "total_storage_used": "Total Storage Used",
        "all_files_option": "All",
        "index_success": "Successfully indexed",
        "index_fail": "Indexing failed",
        "analysis_expander_label": "Temporary Document Analysis (Not Added to Main Library)",
        "analysis_info_ready": "is ready for analysis. You can use the buttons below.",
    }
}

def get_text(lang, key):
    return TRANSLATIONS.get(lang, TRANSLATIONS["en"]).get(key, key)